server.port=${dev.http.port}

management.server.port=${dev.http.port.internal}

mysql.service.host=127.0.0.1
mysql.service.port=3306

inera.idp.client-id=ia.localtest.me
inera.idp.client-secret=a27149c3-a3d1-47cb-bcc2-c31dd5d89c1c
inera.idp.issuer-uri=https://idp.qa.siths.se:443/oidc
inera.idp.logout-redirect-uri=https://ia.localtest.me/#/loggedout/m
inera.idp.redirect-uri=https://ia.localtest.me/login/inera

logging.structured.format.console=

spring.datasource.password=intygsadmin
spring.datasource.username=intygsadmin
spring.output.ansi.enabled=ALWAYS

spring.data.redis.host=localhost
spring.data.redis.password=redis


intygstjansten.internalapi=http://localhost:8180/inera-certificate
privatlakarportal.internalapi=http://localhost:8160
terminationservice.api=http://localhost:18010
webcert.internalapi=http://localhost:8120