app:
  name: intygsadmin

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  forward-headers-strategy: framework

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'health, banner, info, user'

spring:
  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
  profiles:
    active: dev, fake, caching-enabled, it-stub, wc-stub
  h2:
    console:
      enabled: false
  session:
    store-type: redis
    redis:
      namespace: "${app.name}:session"
      flush-mode: immediate

intyg:
  redis:
    sentinel:
      master:
        name: master
    password:
    cache:
      default_entry_expiry_time_in_seconds: 86400
    port: 6379
    host: 127.0.0.1

inera:
  idp:
    client-id: intygsadmindev
    client-secret: f2e71e76-4afa-455e-9b01-9dedead4590b
    redirect-uri: http://localhost:8680/login/inera
    logout-redirect-uri: http://localhost:8680/#/loggedout/m
    issuer-uri: https://idp.ineradev.org:443/oidc

webcert:
  internalapi: http://localhost:9088

intygstjansten:
  internalapi: http://localhost:8080/inera-certificate

job:
  erasetestcertificate:
    cron: "0 0 6 * * *"

erasetestcertificate:
  erase:
    after:
      day: 31