app:
  name: intygsadmin

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
  forward-headers-strategy: framework
  error:
    path: "/error"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'health, banner, info, user'

spring:
  jpa:
    open-in-view: true
  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
  profiles:
    active: dummy
  datasource:
    url: jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${database.name}?useSSL=false&serverTimezone=Europe/Stockholm&allowPublicKeyRetrieval=true
    password:
    username:
  session:
    store-type: redis
    redis:
      namespace: "${app.name}:session"
      flush-mode: immediate

intyg:
  redis:
    sentinel:
      master:
        name: master
    password:
    cache:
      default_entry_expiry_time_in_seconds: 86400
    port: 6379
    host: 127.0.0.1

inera:
  idp:
    client-id: ia.localtest.me
    client-secret: a27149c3-a3d1-47cb-bcc2-c31dd5d89c1c
    redirect-uri: https://ia.localtest.me/login/inera
    logout-redirect-uri: https://ia.localtest.me/#/loggedout/m
    issuer-uri: https://idp.ineratest.org:443/oidc
    client-registration-id: siths
    user-name-attribute-name: employeeHsaId
    scope: openid

webcert:
  internalapi: http://localhost:8120

intygstjansten:
  internalapi: http://localhost:8180/inera-certificate

terminationservice:
  api: http://localhost:18010

privatlakarportal:
  internalapi: http://localhost:8160

job:
  erasetestcertificate:
    cron: "0 0 6 * * *"

erasetestcertificate:
  erase:
    after:
      day: 31

springdoc:
  packagesToScan: se.inera.intyg.intygsadmin.web.controller
  swagger-ui:
    operationsSorter: alpha
