server:
  port: 8680

management:
  server:
    port: 8681
  endpoints:
    web:
      exposure:
        include: 'health, banner, info'

spring:
  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
  profiles:
    active: default, dev
